# generated by datamodel-codegen:
#   filename:  rogue_test_data.json
#   timestamp: 2024-11-04T17:09:31+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, RootModel


class RogueItem(BaseModel):
    acknowledged: bool
    classification: str
    classification_method: str
    containment_status: str
    cust_id: str
    encryption: str
    first_det_device: str
    first_det_device_name: str
    first_seen: str
    id: str
    last_det_device: str
    last_det_device_name: str
    last_seen: str
    mac_vendor: str
    name: str
    overriden: bool
    signal: int
    ssid: Optional[str] = None
    human_first_seen: str
    human_last_seen: str


class RogueModel(RootModel):
    root: List[RogueItem]
